---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mantle-controller
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
      - persistentvolumes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mantle.cybozu.io
    resources:
      - mantlebackupconfigs
      - mantlebackups
      - mantlerestores
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - mantle.cybozu.io
    resources:
      - mantlebackupconfigs/finalizers
      - mantlebackups/finalizers
      - mantlerestores/finalizers
    verbs:
      - update
  - apiGroups:
      - mantle.cybozu.io
    resources:
      - mantlebackupconfigs/status
      - mantlebackups/status
      - mantlerestores/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - mantle.cybozu.io
    resources:
      - mantlerbackup
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
