---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-backup-cybozu-com-v1-rbdpvcbackup
  failurePolicy: Fail
  name: mrbdpvcbackup.kb.io
  rules:
  - apiGroups:
    - backup.cybozu.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rbdpvcbackups
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-backup-cybozu-com-v1-rbdpvcbackup
  failurePolicy: Fail
  name: vrbdpvcbackup.kb.io
  rules:
  - apiGroups:
    - backup.cybozu.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rbdpvcbackups
  sideEffects: None
