replicaCount: 1

image:
  repository: ghcr.io/cybozu-go/mantle
  pullPolicy:
  tag: # {{ .Chart.AppVersion }}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "mantle-controller"

podAnnotations: {}
podLabels: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

controller:
  role: standalone
  ports: []
  env: []

secondaryService:
  # type:
  # port:
  # targetPort:
