# permissions for end users to view mantlerestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mantle
    app.kubernetes.io/managed-by: kustomize
  name: mantlerestore-viewer-role
rules:
- apiGroups:
  - backup.cybozu.io
  resources:
  - mantlerestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backup.cybozu.io
  resources:
  - mantlerestores/status
  verbs:
  - get
