# permissions for end users to edit mantlerestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: mantle
    app.kubernetes.io/managed-by: kustomize
  name: mantlerestore-editor-role
rules:
- apiGroups:
  - backup.cybozu.io
  resources:
  - mantlerestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.cybozu.io
  resources:
  - mantlerestores/status
  verbs:
  - get
