# permissions for end users to view mantlebackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mantlebackup-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mantle
    app.kubernetes.io/part-of: mantle
    app.kubernetes.io/managed-by: kustomize
  name: mantlebackup-viewer-role
rules:
- apiGroups:
  - mantle.cybozu.io
  resources:
  - mantlebackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mantle.cybozu.io
  resources:
  - mantlebackups/status
  verbs:
  - get
