---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - backup.cybozu.com
  resources:
  - rbdpvcbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.cybozu.com
  resources:
  - rbdpvcbackups/finalizers
  verbs:
  - update
- apiGroups:
  - backup.cybozu.com
  resources:
  - rbdpvcbackups/status
  verbs:
  - get
  - patch
  - update
