apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mantle.fullname" . }}-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mantle-controller
subjects:
- kind: ServiceAccount
  name: {{ include "mantle.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mantle.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "mantle.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "mantle.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
