name: "ceph custom export-diff test"
on:
  pull_request:
    paths:
      - "ceph/**"
jobs:
  test:
    runs-on: mantle_large_runner_16core
    steps:
      - run: sudo apt-get update
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - uses: ./.github/actions/set-up-kvm-for-e2e-tests
      - run: make -C ceph setup
      - run: make -C ceph build
      - run: make -C ceph test
