name: "e2e"
on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
  push:
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
    branches:
      - "main"

jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - run: df -h; lsblk
      - uses: actions/checkout@v4
      - run: df -h; lsblk
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - run: df -h; lsblk
      - run: sudo apt update
      - run: sudo apt purge -y --autoremove apport apport-symptoms fwupd nano netplan.io popularity-contest unattended-upgrades update-manager-core snapd
      - run: sudo docker image prune
      - run: df -h; lsblk
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: df -h; lsblk
      - name: cache go dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-${{ hashFiles('go.sum', 'Makefile', 'versions.mk') }}
          restore-keys: |
            go-
      - run: df -h; lsblk
      - run: make -C e2e setup-minikube-upstream-rook
      - run: df -h; lsblk
      - run: make -C e2e test-upstream-rook DOCKER_SAVE_PATH=/mnt
