name: "e2e"
on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
  push:
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
    branches:
      - "main"

jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - run: sudo apt-get update
      - uses: ./.github/actions/purge-unnecessary-deb-packages
      - uses: ./.github/actions/set-up-kvm-for-e2e-tests
      - run: make -C test/e2e setup
      - run: make -C test/e2e test
